application: blog
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets/
  static_dir: templates/css

- url: /scripts/
  static_dir: templates/scripts
  
- url: /
  script: main.py

- url: /postar
  script: /views/view.py
  
- url: /post/delete
  script: /views/view.py
